# config.py - ReGrid 시스템 설정 파일
# 임계값, 핀 설정, 네트워크 설정 등 시스템 파라미터 정의

CURRENT_THRESHOLD = 5.0
CURRENT_MIN = 0.1
VOLTAGE_MIN = 180.0
VOLTAGE_MAX = 250.0

SAMPLE_INTERVAL_SEC = 1.0
FILTER_WINDOW_SIZE = 5
FAULT_CONFIRM_COUNT = 3
NORMAL_CONFIRM_COUNT = 5

RELAY_MAIN = 17
RELAY_BACKUP = 27
RELAY_ACTIVE_HIGH = True

NODE_ID = "node-1"
HOST = "0.0.0.0"
PORT = 5000
PEER_NODES = []

LOG_FILE = "power_data.jsonl"
N8N_WEBHOOK_URL = ""
HTTP_TIMEOUT_SEC = 2.0
